flasky_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired





class PostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired()])
    content = TextAreaField('内容', validators=[DataRequired()])
    submit = SubmitField('发布')

flasky_blog/main/routes.py
from flask import render_template, request, Blueprint
from flasky_blog.models import Post

#from . import main_bp
main_bp = Blueprint('main', __name__)


@main_bp.route("/")
@main_bp.route("/home")
def home():
    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date_posted.desc())\
                      .paginate(page=page,per_page=3)
    return render_template('home.html',posts=posts)

@main_bp.route("/about")
def about():
    return render_template('about.html',title='About')

flasky_blog/posts/__init__.py
# from flask import Blueprint
# 
# 
# posts_bp = Blueprint('posts', __name__)
# 
# from .import routes

flasky_blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flasky_blog import db
from flasky_blog.models import Post
from flasky_blog.posts.forms import PostForm

posts_bp = Blueprint('posts',__name__)
# from . import posts_bp


@posts_bp.route("/post/new",methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,content=form.content.data,\
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("文章已发布",'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form,\
                            legend='发布文章')

@posts_bp.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title='post',post=post)

@posts_bp.route("/post/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('文章已更新', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html',title='update Post',form=form, \
                            legend='修改文章')

@posts_bp.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('文章已经删除', 'success')
    return redirect(url_for('main.home'))

flasky_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flasky_blog import db, bcrypt
from flasky_blog.models import User, Post
from flasky_blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flasky_blog.users.utils import save_picture, send_reset_email



users_bp = Blueprint('users',__name__)

# from . import users_bp



@users_bp.route("/register",methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        #flash(f'账户已经为{form.username.data}创建!','success')
        hashed_password = bcrypt.generate_password_hash(form.password.data).\
                          decode('utf-8')
        user = User(username=form.username.data,email=form.email.data,\
               password = hashed_password  )
        db.session.add(user)
        db.session.commit()
        flash(f'{form.username.data} 您好，账户已经为您创建', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html',title='register',form=form)


@users_bp.route("/login",methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,\
                                                form.password.data):
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(\
                                                        url_for('main.home'))
            #return redirect(url_for('home'))
        else:
            flash('登录失败，请检查您的邮箱和密码是否正确，谢谢！','danger')
    return render_template('login.html',title='About',form=form)


@users_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users_bp.route("/account",methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('个人信息已成功更新!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username 
        form.email.data = current_user.email
    image_file = url_for('static',filename='images/' + current_user.image_file)
    return render_template('account.html',title='Account',\
                                        image_file=image_file,form=form)







@users_bp.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=3)
    return render_template('user_posts.html', posts=posts, user=user)






@users_bp.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('重置密码的邮件已经发送到您的指定邮箱，请移步查看！', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', \
                            form=form)


@users_bp.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).\
                                                        decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('您的密码已更新! 现在可以重新登录！！！', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='密码重置', form=form)

flasky_blog/templates/about.html
{% extends "base.html" %}
{% block content %}
	<h1>About Page</h1> 
{% endblock  content %}

flasky_blog/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
            <div class="media">
            <img class="rounded-circle account-img " src="{{ image_file }}">
            <div class="media-body">
                    <h2 class="account-heading">{{ current_user.username }}</h2>
                    <p class="text-secondary">{{ current_user.email }}</p>
            </div>
            </div>
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">用户信息</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label")}}
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for errors in form.username.errors %}
                                        <span>{{ errors }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg")}}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label")}}
                            {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for errors in form.email.errors %}
                                    <span>{{ errors }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.email(class="form-control form-control-lg")}}
                        {% endif %}
                        <div class="form-group">
                                {{ form.picture.label() }}
                                {{ form.picture(class="form-control-file") }}
                                {% if form.picture.errors %}
                                    {% for errors in form.picture.errors %}
                                        <span class="text-danger">{{ errors }}</span>
                                    {% endfor %}
                                {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
{% endblock  content %}

flasky_blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome.min.css') }}"> -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">我的博客</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">主页</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">关于</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">用户</a>
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">发布博客</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">退出</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">登录</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">注册</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
		  	    {% for category, message in messages %}
		  		  <div class="alert alert-{{ category }}">
					    {{ message }}
            </div>
            {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.slim.min.js') }}" ></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

flasky_blog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label")}}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.title.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label")}}
                    {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.content.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.content(class="form-control form-control-lg",cols="10", rows="15") }}
                {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock  content %}

flasky_blog/templates/home.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static',filename='images/' + post.author.image_file)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

flasky_blog/templates/login.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">登 录</legend>
                <div class="form-group">
                        <span class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                        </span>
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.email.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group">
                    <span class="input-group-addon">
                        <i class="fa fa-lock"></i>
                    </span>
                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.password.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">忘记密码</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                注册账户<a class="ml-2" href="{{ url_for('users.register') }}">现在注册</a>
            </small>
        </div>
    </div>
{% endblock  content %}

flasky_blog/templates/post.html
{% extends "base.html" %}
{% block content %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static',filename='images/' + post.author.image_file)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
              {% if post.author == current_user %}
              <div class="btn-group" role="group">
                <a class="btn btn-secondary btn-sm m-1 " href="{{ url_for('posts.update_post', post_id=post.id) }}">修改</a>
                <button type="button" class="btn btn-danger btn-sm m-1 " data-toggle="modal" data-target="#deleteModal"><i class="fa fa-trash-o fa-sm"></i>删除</button>
              </div>
              {% endif %}
            </div>
            <div><h2><a class="article-title">{{ post.title }}</a></h2></div>
            <div><p class="article-content">{{ post.content }}</p></div>
          </div>
        </article>
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">是否删除该博客?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                  <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="删除">
                  </form>
                </div>
              </div>
            </div>
        </div>
{% endblock content %}

flasky_blog/templates/register.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label")}}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for errors in form.username.errors %}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.email.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.password.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label")}}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for errors in form.confirm_password.errors %}
                            <span>{{ errors }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg")}}
                {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock  content %}

flasky_blog/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">重置密码</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

flasky_blog/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">重置密码</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flasky_blog/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}